# Generated by Django 5.0.7 on 2024-08-08 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_user_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('post', models.CharField(max_length=30)),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_name', to='django_app.user')),
            ],
        ),
    ]
